spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
